name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.14
    - name: Install Python dependencies
      run: |
        pip install httpx
        pip install beautifulsoup4
    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python build.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "0xcaffebabe-bot"
        git config --global user.name "0xcaffebabe-bot"
        git pull
        git add -A
        git commit -m "Updated README" || exit 0
        git push
